@echo off
echo Starting IntelliLend Backend with IOTA Integration (Enhanced Version)...
cd %~dp0
echo Checking for dependencies...
npm install --no-save
echo Applying IOTA integration fixes...
node apply-iota-fixes.js
echo Initializing IOTA connections...
set NODE_OPTIONS=--require ./server-patch.js
node backend/server.js