@echo off
echo Starting IntelliLend Backend with IOTA Integration (Fixed Version)...
cd %~dp0
echo Checking for dependencies...
npm install --no-save
echo Applying IOTA integration fixes...
echo Initializing IOTA connections...
node -e "require('./iota-fix-patch'); require('./backend/server.js')"